/* __USER__ */
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const VERIFY = "VERIFY"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const CLEAN_USER_DATA = "CLEAN_USER_DATA"
export const LOGOUT = "LOGOUT"
export const TOKEN = "TOKEN"

/* __FRIEND__ */
export const FRIEND_GET = "FRIEND_GET"
export const FRIEND_SETNICKNAME = "FRIEND_SETNICKNAME"
export const FRIEND_REMOVE = "FRIEND_REMOVE"
export const FRIEND_PUSH = "FRIEND_PUSH"
export const FRIEND_POP = "FRIEND_POP"
export const FRIEND_SENDFRIENDREQUEST = "FRIEND_SENDFRIENDREQUEST"
export const FRIEND_ACCEPTFRIENDREQUEST = "FRIEND_ACCEPTFRIENDREQUEST"
export const FRIEND_REFUSEFRIENDREQUEST = "FRIEND_REFUSEFRIENDREQUEST"
export const FRIEND_CANCELFRIENDREQUEST = "FRIEND_CANCELFRIENDREQUEST"
export const FRIEND_UPDATE_DATA = "FRIEND_UPDATE_DATA"  //Call while transmit

/* __FRIEND_REQUEST__ */
export const FRIENDREQUEST_GET = 'FRIENDREQUEST_GET'
export const FRIENDREQUEST_PUSH_RECEVICE = 'FRIENDREQUEST_PUSH_RECEVICE'
export const FRIENDREQUEST_PUSH_SENT = 'FRIENDREQUEST_PUSH_SENT'
export const FRIENDREQUEST_POP_RECEVICE = 'FRIENDREQUEST_POP_RECEVICE'
export const FRIENDREQUEST_POP_SENT = 'FRIENDREQUEST_POP_SENT'

/* __APP_DATA__ */
export const INITIALIZE = "INITIALIZE"
export const PUSH_TOAST = "PUSH_TOAST"
export const TOGGLE_SOUND = "TOGGLE_SOUND"
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION"
export const CLOSE_POPUP = "CLOSE_POPUP"
export const OPEN_POPUP = "OPEN_POPUP"
export const CLOSE_DIALOG = "CLOSE_DIALOG"
export const OPEN_DIALOG = "OPEN_DIALOG"

/* __NAVIGATION__ */
export const CHOOSE_CONTENT_TAB = "CHOOSE_CONTENT_TAB"
export const CHOOSE_PEOPLE_TAB = "CHOOSE_PEOPLE_TAB"