/* __USER__ */
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const VERIFY = "VERIFY"
export const CLEAN_USER_DATA = "CLEAN_USER_DATA"
export const LOGOUT = "LOGOUT"
export const TOKEN = "TOKEN"

/* __FRIEND__ */
export const FRIEND_GET = "FRIEND_GET"
export const FRIEND_SETNICKNAME = "FRIEND_SETNICKNAME"
export const FRIEND_REMOVE = "FRIEND_REMOVE"
export const FRIEND_SENDFRIENDREQUEST = "FRIEND_SENDFRIENDREQUEST"
export const FRIEND_ACCEPTFRIENDREQUEST = "FRIEND_ACCEPTFRIENDREQUEST"
export const FRIEND_REFUSEFRIENDREQUEST = "FRIEND_REFUSEFRIENDREQUEST"
export const FRIEND_CANCELFRIENDREQUEST = "FRIEND_CANCELFRIENDREQUEST"
export const FRIEND_UPDATE_DATA = "FRIEND_UPDATE_DATA"

/* __APP_DATA__ */
export const INITIALIZE = "INITIALIZE"

/* __NAVIGATION__ */
export const CHOOSE_CONTENT_TAB = "CHOOSE_CONTENT_TAB"
export const CHOOSE_PEOPLE_TAB = "CHOOSE_PEOPLE_TAB"