/* __USER__ */
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const VERIFY = "VERIFY"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const CLEAN_USER_DATA = "CLEAN_USER_DATA"
export const LOGOUT = "LOGOUT"
export const TOKEN = "TOKEN"

/* __FRIEND__ */
export const FRIEND_GET = "FRIEND_GET"
export const FRIEND_SETNICKNAME = "FRIEND_SETNICKNAME"
export const FRIEND_REMOVE = "FRIEND_REMOVE"
export const FRIEND_PUSH = "FRIEND_PUSH"
export const FRIEND_POP = "FRIEND_POP"
export const FRIEND_SENDFRIENDREQUEST = "FRIEND_SENDFRIENDREQUEST"
export const FRIEND_ACCEPTFRIENDREQUEST = "FRIEND_ACCEPTFRIENDREQUEST"
export const FRIEND_REFUSEFRIENDREQUEST = "FRIEND_REFUSEFRIENDREQUEST"
export const FRIEND_CANCELFRIENDREQUEST = "FRIEND_CANCELFRIENDREQUEST"
export const FRIEND_UPDATE_DATA = "FRIEND_UPDATE_DATA"  //Call while transmit

/* __FRIEND_REQUEST__ */
export const FRIENDREQUEST_GET = 'FRIENDREQUEST_GET'
export const FRIENDREQUEST_PUSH_RECEVICE = 'FRIENDREQUEST_PUSH_RECEVICE'
export const FRIENDREQUEST_PUSH_SENT = 'FRIENDREQUEST_PUSH_SENT'
export const FRIENDREQUEST_POP_RECEVICE = 'FRIENDREQUEST_POP_RECEVICE'
export const FRIENDREQUEST_POP_SENT = 'FRIENDREQUEST_POP_SENT'

/* __FRIEND_REQUEST__ */
export const CHATROOM_CREATE = "CHATROOM_CREATE"
export const CHATROOM_UNFOLLOW = "CHATROOM_UNFOLLOW"
export const CHATROOM_INVITE = "CHATROOM_INVITE"
export const CHATROOM_GETALLUSERCHATROOMS = "CHATROOM_GETALLUSERCHATROOMS"
export const CHATROOM_UPDATE = "CHATROOM_UPDATE"

/* __APP_DATA__ */
export const INITIALIZE = "INITIALIZE"
export const PUSH_TOAST = "PUSH_TOAST"
export const TOGGLE_SOUND = "TOGGLE_SOUND"
export const SET_VIEW_TYPE = "SET_VIEW_TYPE"
export const SET_UNREAD_STATE = "SET_UNREAD_STATE"
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION"
export const CLOSE_POPUP = "CLOSE_POPUP"
export const OPEN_POPUP = "OPEN_POPUP"
export const CLOSE_DIALOG = "CLOSE_DIALOG"
export const OPEN_DIALOG = "OPEN_DIALOG"

/* __MESSAGE__ */
export const MESSAGE_GET = "MESSAGE_GET"
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE"

/* __TYPING__ */
export const TYPING = "TYPING"

/* __NAVIGATION__ */
export const CHOOSE_CONTENT_TAB = "CHOOSE_CONTENT_TAB"
export const CHOOSE_PEOPLE_TAB = "CHOOSE_PEOPLE_TAB"
export const NAVIGATOR_SET_CHATROOM = "NAVIGATOR_SET_CHATROOM"
export const SET_CONVERSATION_VIEW = "SET_CONVERSATION_VIEW"
export const OPEN_SUBVIEW = "OPEN_SUBVIEW"
export const CLOSE_SUBVIEW = "CLOSE_SUBVIEW"